image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
  - command: npm install
    command: gulp
    command: firebase serve
    name: server

ports:
  - port: 5000
    onOpen: open-browser
