--- 
image: 
  file: .gitpod.Dockerfile
ports: 
  - port: 5000
    onOpen: open-browser
tasks: 
  - init: npm install
    command: python3 main.py
  - command: npm install
    command: npm run build
    command: npm run serve
